"""Abstract driver protocols. Types for real and mock implementations."""

from typing import Protocol, runtime_checkable
import numpy as np

from PySide6.QtCore import Signal

@runtime_checkable
class SangaboardProtocol(Protocol):
    """Serial motor controller (Sangaboard firmware)."""
    position_updated: Signal  # (int, int, int): x, y, z
    connected_changed: Signal  # (bool)
    motion_timing_updated: Signal  # (int, int): step_time_us, ramp_time_us

    def move_rel(self, dx: int, dy: int, dz: int, coalesce: bool = False) -> None: ...
    def move_rel_blocking(self, dx: int, dy: int, dz: int, timeout: float | None = None) -> bool: ...
    def request_motion_timing(self) -> None: ...
    def set_step_time_us(self, value: int) -> None: ...
    def set_ramp_time_us(self, value: int) -> None: ...
    def zero_position(self) -> None: ...
    def stop_motors(self) -> None: ...
    def release_motors(self) -> None: ...
    def request_stop(self) -> None: ...
    def start(self) -> None: ...
    def wait(self, msecs: int = -1) -> bool: ...

@runtime_checkable
class ADCProtocol(Protocol):
    """Two-axis joystick ADC (ADS1115)."""
    axes_updated: Signal  # (int, int): raw 16-bit signed x, y

    def inject_axes(self, x: int, y: int) -> None: ...
    def request_stop(self) -> None: ...
    def start(self) -> None: ...
    def wait(self, msecs: int = -1) -> bool: ...

@runtime_checkable
class EncoderProtocol(Protocol):
    """Rotary encoder + endstop."""
    stepped: Signal       # (int): signed delta ticks
    endstop_changed: Signal  # (bool): True = triggered

    def simulate_step(self, delta: int) -> None: ...
    def simulate_endstop(self, triggered: bool) -> None: ...
    def request_stop(self) -> None: ...
    def start(self) -> None: ...
    def wait(self, msecs: int = -1) -> bool: ...

@runtime_checkable
class CameraProtocol(Protocol):
    """Video frame source."""
    frame_ready: Signal

    def capture_snapshot(self) -> "np.ndarray | None": ...
    def request_stop(self) -> None: ...
    def start(self) -> None: ...
    def wait(self, msecs: int = -1) -> bool: ...
